"""auditoria de promociones

Revision ID: 338acb94c91d
Revises: ecf265ab79e6
Create Date: 2026-06-26 08:42:29.304927

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '338acb94c91d'
down_revision: str | None = 'ecf265ab79e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_change_log',
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('created', 'updated', 'deleted', name='promotionaction'), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('origin', sa.Enum('chat', 'manual', 'suggestion', 'rollback', name='changeorigin'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_change_log_changed_at'), 'promotion_change_log', ['changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_change_log_changed_at'), table_name='promotion_change_log')
    op.drop_table('promotion_change_log')
    # ### end Alembic commands ###
