"""modelo de datos inicial

Revision ID: 4d444884ea03
Revises: 
Create Date: 2026-06-24 15:24:05.006526

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '4d444884ea03'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('kind', sa.Enum('concert', 'fair', 'convention', 'holiday', 'festival', 'other', name='eventkind'), nullable=False),
    sa.Column('relevance', sa.Enum('low', 'medium', 'high', name='relevance'), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('dedup_key', sa.String(length=400), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_dedup_key'), 'event', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_event_start_date'), 'event', ['start_date'], unique=False)
    op.create_table('llm_config',
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model_general', sa.String(length=80), nullable=False),
    sa.Column('model_actions', sa.String(length=80), nullable=False),
    sa.Column('budget_usd_per_day', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='propertystatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('booking', 'airbnb', 'direct', name='channelkind'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('price_offset_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'kind', name='uq_channel_property_kind')
    )
    op.create_table('message',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_table('pricing_rule',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parity_notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rule_property_id'), 'pricing_rule', ['property_id'], unique=False)
    op.create_table('promotion',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('discount_type', sa.Enum('percent', 'amount', name='promotiontype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='promotionstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_property_id'), 'promotion', ['property_id'], unique=False)
    op.create_table('unit_type',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('units_count', sa.Integer(), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('channel_kind', sa.Enum('booking', 'airbnb', 'direct', name='channelkind'), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'pending', name='bookingstatus'), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_unit_type_id'), 'booking', ['unit_type_id'], unique=False)
    op.create_table('calendar_day',
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_type_id', 'date', name='uq_calendarday_unit_date')
    )
    op.create_index(op.f('ix_calendar_day_date'), 'calendar_day', ['date'], unique=False)
    op.create_index(op.f('ix_calendar_day_unit_type_id'), 'calendar_day', ['unit_type_id'], unique=False)
    op.create_table('price_suggestion',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_type_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('suggested_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'applied', name='suggestionstatus'), nullable=False),
    sa.Column('applied_change_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_suggestion_property_id'), 'price_suggestion', ['property_id'], unique=False)
    op.create_table('rate',
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_type_id', 'date', name='uq_rate_unit_date')
    )
    op.create_index(op.f('ix_rate_date'), 'rate', ['date'], unique=False)
    op.create_index(op.f('ix_rate_unit_type_id'), 'rate', ['unit_type_id'], unique=False)
    op.create_table('price_change_log',
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('origin', sa.Enum('chat', 'manual', 'suggestion', 'rollback', name='changeorigin'), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('reverts_change_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['reverts_change_id'], ['price_change_log.id'], ),
    sa.ForeignKeyConstraint(['suggestion_id'], ['price_suggestion.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_change_log_changed_at'), 'price_change_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_price_change_log_date'), 'price_change_log', ['date'], unique=False)
    op.create_index(op.f('ix_price_change_log_unit_type_id'), 'price_change_log', ['unit_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_change_log_unit_type_id'), table_name='price_change_log')
    op.drop_index(op.f('ix_price_change_log_date'), table_name='price_change_log')
    op.drop_index(op.f('ix_price_change_log_changed_at'), table_name='price_change_log')
    op.drop_table('price_change_log')
    op.drop_index(op.f('ix_rate_unit_type_id'), table_name='rate')
    op.drop_index(op.f('ix_rate_date'), table_name='rate')
    op.drop_table('rate')
    op.drop_index(op.f('ix_price_suggestion_property_id'), table_name='price_suggestion')
    op.drop_table('price_suggestion')
    op.drop_index(op.f('ix_calendar_day_unit_type_id'), table_name='calendar_day')
    op.drop_index(op.f('ix_calendar_day_date'), table_name='calendar_day')
    op.drop_table('calendar_day')
    op.drop_index(op.f('ix_booking_unit_type_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('unit_type')
    op.drop_index(op.f('ix_promotion_property_id'), table_name='promotion')
    op.drop_table('promotion')
    op.drop_index(op.f('ix_pricing_rule_property_id'), table_name='pricing_rule')
    op.drop_table('pricing_rule')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_table('channel')
    op.drop_table('property')
    op.drop_table('llm_config')
    op.drop_index(op.f('ix_event_start_date'), table_name='event')
    op.drop_index(op.f('ix_event_dedup_key'), table_name='event')
    op.drop_table('event')
    op.drop_table('conversation')
    # ### end Alembic commands ###
