"""availability change log

Revision ID: 7d3816a7c205
Revises: cd5dfcfbaceb
Create Date: 2026-06-28 11:05:15.745076

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '7d3816a7c205'
down_revision: str | None = 'cd5dfcfbaceb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_change_log',
    sa.Column('unit_type_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('old_units_available', sa.Integer(), nullable=True),
    sa.Column('new_units_available', sa.Integer(), nullable=False),
    sa.Column('was_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    # El tipo enum 'changeorigin' ya existe (price_change_log); no recrearlo.
    sa.Column('origin', postgresql.ENUM('chat', 'manual', 'suggestion', 'rollback', name='changeorigin', create_type=False), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['unit_type_id'], ['unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_change_log_changed_at'), 'availability_change_log', ['changed_at'], unique=False)
    op.create_index(op.f('ix_availability_change_log_date'), 'availability_change_log', ['date'], unique=False)
    op.create_index(op.f('ix_availability_change_log_unit_type_id'), 'availability_change_log', ['unit_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_change_log_unit_type_id'), table_name='availability_change_log')
    op.drop_index(op.f('ix_availability_change_log_date'), table_name='availability_change_log')
    op.drop_index(op.f('ix_availability_change_log_changed_at'), table_name='availability_change_log')
    op.drop_table('availability_change_log')
    # ### end Alembic commands ###
