"""intelligence run + market reference

Revision ID: cd5dfcfbaceb
Revises: 248395fee3e4
Create Date: 2026-06-26 10:36:48.532104

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cd5dfcfbaceb'
down_revision: str | None = '248395fee3e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_run',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'error', name='syncstatus'), nullable=False),
    sa.Column('events_found', sa.Integer(), nullable=False),
    sa.Column('suggestions_created', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_reference',
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_reference_zone'), 'market_reference', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_reference_zone'), table_name='market_reference')
    op.drop_table('market_reference')
    op.drop_table('intelligence_run')
    # ### end Alembic commands ###
