"""conector beds24 (sync)

Revision ID: ecf265ab79e6
Revises: 4d444884ea03
Create Date: 2026-06-24 17:09:56.258854

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ecf265ab79e6'
down_revision: str | None = '4d444884ea03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_manager_connection',
    sa.Column('provider', sa.Enum('beds24', name='provider'), nullable=False),
    sa.Column('status', sa.Enum('unconfigured', 'connected', 'invalid', name='connectionstatus'), nullable=False),
    sa.Column('credentials_ref', sa.String(length=120), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_run',
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='syncdirection'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'error', name='syncstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_issue',
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('comm_error', 'auth_error', 'price_discrepancy', 'write_unverified', 'rate_limited', name='syncissuekind'), nullable=False),
    sa.Column('entity_ref', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='issuestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_issue')
    op.drop_table('sync_run')
    op.drop_table('channel_manager_connection')
    # ### end Alembic commands ###
